@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc3NzI1MTN9._-yE_7TjK3vgpZSIImwB1yZ-vqyfWbzKrFj1TyNXRA4

# To use them use {{jwt}}
# admin
# test = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2Mzc3NzI1MTN9._-yE_7TjK3vgpZSIImwB1yZ-vqyfWbzKrFj1TyNXRA4

#user
# test1 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2Mzc3NzI1NDN9.O4ltczPb7fg5puaQssRZ2ZTszy4RoVHmVoOSwrNQHKc

#user
# test2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2Mzc3NzI1NTF9.xbYBM-OWfWmFYuZGIot46mqhKloSE3PMmtUzhqeXzxA

###
#products index
GET http://localhost:3000/products.json?category=electronics
Authorization: Bearer {{jwt}}

###
# products show
GET http://localhost:3000/products/1.json
Authorization: Bearer {{jwt}}

###
# products create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "name": "TABle",
  "price": 100,
  "description": "Holds things",
  "supplier_id": 5
}

###
# products update
PATCH http://localhost:3000/products/51.json
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "name": "BEEr",
  "price": 5,
  "description": "picture of budweiser",
  "supplier_id": 1,
  "image_url": "https://us.budweiser.com/content/dam/brand-template/budweiser/history/desktop/Budweiser_Desktop_Heritage_BuyBeer.jpg"
}

###
# products delete
DELETE http://localhost:3000/products/117
Authorization: Bearer {{jwt}}

###
# user signup
POST http://localhost:3000/users
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "name": "Test2",
  "email": "test2@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###
# user login
POST http://localhost:3000/sessions
content-type: application/json

{
  "email": "test2@gmail.com",
  "password": "password"
}

###
# create order
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
content-type: application/json 

{
  "product_id": 9,
  "quantity": 2
}

###
# show order
GET http://localhost:3000/orders/4
Authorization: Bearer {{jwt}}

###
# update order
PATCH http://localhost:3000/orders/4
Authorization: Bearer {{jwt}}
content-type: application/json 

{
  "quantity": 2
}

###
# order index - not working - column orders.user_id does not exist
GET http://localhost:3000/orders 
Authorization: Bearer {{jwt}}

###
# carted_products create
POST http://localhost:3000/carted_products
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "product_id": 3,
  "quantity": 1
}