@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUzNTIwNDV9.HV08QR9XrCVQ4HbfdRdmruIwE_8c-tFoZLPI2uZNZys

###
#products index
GET http://localhost:3000/products.json
Authorization: Bearer {{jwt}}

###
# products show
GET http://localhost:3000/products/1.json
Authorization: Bearer {{jwt}}

###
# products create
POST http://localhost:3000/products.json
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "name": "TABle",
  "price": 100,
  "description": "Holds things",
  "supplier_id": 5
}

###
# products update
PATCH http://localhost:3000/products/51.json
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "name": "BEEr",
  "price": 5,
  "description": "picture of budweiser",
  "supplier_id": 1,
  "image_url": "https://us.budweiser.com/content/dam/brand-template/budweiser/history/desktop/Budweiser_Desktop_Heritage_BuyBeer.jpg"
}

###
# products delete
DELETE http://localhost:3000/products/117
Authorization: Bearer {{jwt}}

###
# user signup
POST http://localhost:3000/users
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "name": "Test2",
  "email": "test2@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

###
# user login
POST http://localhost:3000/sessions
Authorization: Bearer {{jwt}}
content-type: application/json

{
  "email": "test2@gmail.com",
  "password": "password"
}

###
# create order
POST http://localhost:3000/orders
Authorization: Bearer {{jwt}}
content-type: application/json 

{
  "product_id": 7,
  "quantity": 2
}

###
# show order
GET http://localhost:3000/orders/4
Authorization: Bearer {{jwt}}

###
# update order
PATCH http://localhost:3000/orders/4
Authorization: Bearer {{jwt}}
content-type: application/json 

{
  "quantity": 2
}

###
# order index
GET http://localhost:3000/orders 
Authorization: Bearer {{jwt}}

# To use them use {{}}
# admin
# test = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUzNTIwMTZ9.LtXjSBxLMEaW9IwuhmiCi6Vhqj79rq6UMXBngP0dkhA

# test1 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzUzNTIwNDV9.HV08QR9XrCVQ4HbfdRdmruIwE_8c-tFoZLPI2uZNZys

# test2 = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2MzUzNTIwODd9.-JYoIkM-fOcbR-ILRelXchRSKgMfaIv28uA1bup3oV4